version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: yarn install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Audit vulnerabilities
          command: yarn audit
      - run:
          name: Static code analyze
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test
