version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.16.3

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: yarn install --ignore-scripts --frozen-lockfile
      - run:
          name: Audit vulnerabilities
          command: yarn audit
      - run:
          name: Static code analyze
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test
      - run:
          name: Repost coverage
          command: ./node_modules/.bin/codecov --token="$CODECOV_TOKEN"
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish package
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2.1
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
