version: 2
jobs:
  build:
    working_directory: ~/src

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      - run:
          name: Install dependencies
          command: yarn install --ignore-scripts

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Audit vulnerabilities
          command: yarn audit

      - run:
          name: Static code analyze
          command: yarn lint

      - run:
          name: Unit tests
          command: yarn test
